<script lang="ts">
    let name = "";
    let email = "";
    let contentTitle = "";
    let contentDescription = "";
    let royaltyPercentage = 50; // Default royalty percentage
    let termsAccepted = false;
  
    function submitContent(event: Event) {
      event.preventDefault();
      if (!termsAccepted) {
        alert("Please accept the terms and conditions before submitting.");
        return;
      }
      // Replace with your backend API integration
      console.log({
        name,
        email,
        contentTitle,
        contentDescription,
        royaltyPercentage,
      });
      alert("Thank you for submitting your content! We'll review it and get back to you soon.");
      name = "";
      email = "";
      contentTitle = "";
      contentDescription = "";
      royaltyPercentage = 50;
      termsAccepted = false;
    }
  </script>
  
  <section class="flex flex-col items-center justify-center min-h-screen bg-gray-50 px-6 py-12">
    <div class="w-full max-w-4xl bg-white rounded-2xl shadow-lg p-8">
      <h1 class="text-2xl font-bold text-center text-gray-800 mb-6">Sell Your Content</h1>
      <p class="text-center text-gray-600 mb-8">
        Share your creative content with our platform and earn royalties. Fill out the form below to get started!
      </p>
      <form on:submit|preventDefault={submitContent} class="space-y-6">
        <div>
          <label for="name" class="block text-sm font-medium text-gray-700 mb-1">Your Name</label>
          <input
            id="name"
            type="text"
            bind:value={name}
            placeholder="Enter your name"
            class="block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 text-gray-800 focus:ring focus:ring-blue-300 focus:outline-none"
            required
          />
        </div>
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 mb-1">Your Email</label>
          <input
            id="email"
            type="email"
            bind:value={email}
            placeholder="Enter your email"
            class="block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 text-gray-800 focus:ring focus:ring-blue-300 focus:outline-none"
            required
          />
        </div>
        <div>
          <label for="contentTitle" class="block text-sm font-medium text-gray-700 mb-1">Content Title</label>
          <input
            id="contentTitle"
            type="text"
            bind:value={contentTitle}
            placeholder="Enter the title of your content"
            class="block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 text-gray-800 focus:ring focus:ring-blue-300 focus:outline-none"
            required
          />
        </div>
        <div>
          <label for="contentDescription" class="block text-sm font-medium text-gray-700 mb-1">Content Description</label>
          <textarea
            id="contentDescription"
            bind:value={contentDescription}
            placeholder="Describe your content"
            rows="5"
            class="block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 text-gray-800 focus:ring focus:ring-blue-300 focus:outline-none"
            required
          ></textarea>
        </div>
        <div>
          <label for="royaltyPercentage" class="block text-sm font-medium text-gray-700 mb-1">Royalty Percentage</label>
          <input
            id="royaltyPercentage"
            type="range"
            min="10"
            max="90"
            bind:value={royaltyPercentage}
            class="w-full"
          />
          <p class="text-gray-600 text-sm mt-1">You will earn {royaltyPercentage}% of the revenue generated by your content.</p>
        </div>
        <div class="flex items-center">
          <input
            id="terms"
            type="checkbox"
            bind:checked={termsAccepted}
            class="mr-2"
          />
          <label for="terms" class="text-sm text-gray-700">
            I agree to the <a href="/terms" class="text-blue-600 hover:underline">terms and conditions</a>.
          </label>
        </div>
        <button
          type="submit"
          class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg shadow focus:ring focus:ring-blue-300 focus:outline-none"
        >
          Submit Your Content
        </button>
      </form>
    </div>
  </section>
  